version: '3.8'
services:
  banking-app:
    image: banking-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - banking-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://banking-db:5432/banking-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  banking-db:
    image: postgres
    environment:
      POSTGRES_DB: banking-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - banking-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  banking-db-data: